### ISSUE TITLE
汉化很棒，但是这个Jar打不开

### ISSUE THREAD

**Issue by Jack-Myth** [pingfangx/TranslatorX#1]
有如下的Log：
WARNING: Resource "com/sun/javafx/scene/control/skin/modena/modena.css" not found.
Exception in Application start method
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: org/dtools/ini/IniFile
        at com.pingfangx.tools.MainSceneController.initialize(MainSceneController.java:82)
        at javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
        at javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
        at javafx.fxml.FXMLLoader.load(Unknown Source)
        at com.pingfangx.tools.Main.start(Main.java:14)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$11(Unknown Source)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$9(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
        ... 1 more
Caused by: java.lang.ClassNotFoundException: org.dtools.ini.IniFile
        at java.base/java.net.URLClassLoader.findClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 14 more

emmm我用的是JDK9，会不会跟JDK的版本有关系？

**Comment by pingfangx** [comment]
你好，是因为引用的 jar 包的问题，附件中将引用的 jar 包单独出去，你下载解压后再试一下，感谢反馈。
[AndroidStudioTranslatorX.zip](https://github.com/pingfangx/TranslatorX/files/1452675/AndroidStudioTranslatorX.zip)

**Comment by Jack-Myth** [comment]
@pingfangx 可以使用了，谢谢~
